Testing: print matrix from build_images #2311

diff --git a/.github/workflows/autotest.yml b/.github/workflows/autotest.yml
--- a/.github/workflows/autotest.yml
+++ b/.github/workflows/autotest.yml
@@ -15,7 +15,7 @@ jobs:
         run: python3 -m pip install -U PyYAML
       - name: Identify Matrix
         id: matrix
-        run: echo "::set-output name=matrix::$(./tools/test/matrix_parser.py < ./etc/docker/test/matrix.yml)"
+        run: echo "::set-output name=matrix::$(jq -c '[.[]  | select(.SUITE=="integration-test")]' <<< $(./tools/test/matrix_parser.py < ./etc/docker/test/matrix.yml))"
     outputs:
       matrix: ${{ steps.matrix.outputs.matrix }}
   test:
@@ -34,21 +34,23 @@ jobs:
           echo "${{ needs.setup.outputs.matrix }}"
           echo "*****"
           echo "${{ matrix.cfg }}"
-#          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
-#          i=0; until [ "$i" -ge 3 ]; do
-#            IMAGES=$(echo '${{ toJson(matrix.cfg) }}' | ./tools/test/build_images.py \
-#                --cache-repo docker.pkg.github.com/${{ github.repository }} ./etc/docker/test || echo "")
-#            if [[ -n $IMAGES ]]; then break;
-#            else
-#              i=$((i+1)); sleep 5;
-#              echo "::warning::Building images failed, retrying…"
-#            fi
-#          done
-#          docker logout https://docker.pkg.github.com
-#          if [[ -z $IMAGES ]]; then exit 1; fi
-#          echo "::set-output name=images::$IMAGES"
-#      - name: Run test with cfg
-#        run: 'echo ''{"matrix": ${{ toJson(matrix.cfg) }}, "images": ${{ steps.images.outputs.images }} }'' | ./tools/test/run_tests.py'
+          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+          i=0; until [ "$i" -ge 3 ]; do
+            IMAGES=$(echo '${{ toJson(matrix.cfg) }}' | ./tools/test/build_images.py \
+                --cache-repo docker.pkg.github.com/${{ github.repository }} ./etc/docker/test || echo "")
+            if [[ -n $IMAGES ]]; then break;
+            else
+              i=$((i+1)); sleep 5;
+              echo "::warning::Building images failed, retrying…"
+            fi
+          done
+          docker logout https://docker.pkg.github.com
+          if [[ -z $IMAGES ]]; then exit 1; fi
+          echo "::set-output name=images::$IMAGES"
+      - name: Run test with cfg
+        run: |
+           echo ''{"matrix": ${{ toJson(matrix.cfg) }}, "images": ${{ steps.images.outputs.images }} }''
+#         'echo ''{"matrix": ${{ toJson(matrix.cfg) }}, "images": ${{ steps.images.outputs.images }} }'' | ./tools/test/run_tests.py'
 #  release-patch-setup:
 #    if: 'github.event_name == ''pull_request'' && !startsWith(github.event.pull_request.base.ref, ''release'') && !startsWith(github.event.pull_request.head.ref, ''feature'')'
 #    runs-on: ubuntu-latest
