Testing: test jq #2311

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -25,31 +25,29 @@ jobs:
   integration-tests:
     needs: setup
     runs-on: ubuntu-latest
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        cfg: ${{ fromJson(needs.setup.outputs.matrix) }}
+    strategy:
+      fail-fast: false
+      matrix:
+        cfg: ${{ fromJson(needs.setup.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v2
       - name: Build images
         id: images
         shell: bash
         run: |
-          echo "${{ needs.setup.outputs.matrix }}"
-#        run: |
-#          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
-#          i=0; until [ "$i" -ge 3 ]; do
-#            IMAGES=$(echo '${{ toJson(matrix.cfg) }}' | ./tools/test/build_images.py \
-#                --cache-repo docker.pkg.github.com/${{ github.repository }} ./etc/docker/test || echo "")
-#            if [[ -n $IMAGES ]]; then break;
-#            else
-#              i=$((i+1)); sleep 5;
-#              echo "::warning::Building images failed, retrying…"
-#            fi
-#          done
-#          docker logout https://docker.pkg.github.com
-#          if [[ -z $IMAGES ]]; then exit 1; fi
-#          echo "::set-output name=images::$IMAGES"
+          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+          i=0; until [ "$i" -ge 3 ]; do
+            IMAGES=$(echo '${{ toJson(matrix.cfg) }}' | ./tools/test/build_images.py \
+                --cache-repo docker.pkg.github.com/${{ github.repository }} ./etc/docker/test || echo "")
+            if [[ -n $IMAGES ]]; then break;
+            else
+              i=$((i+1)); sleep 5;
+              echo "::warning::Building images failed, retrying…"
+            fi
+          done
+          docker logout https://docker.pkg.github.com
+          if [[ -z $IMAGES ]]; then exit 1; fi
+          echo "::set-output name=images::$IMAGES"
 #    steps:
 #      - name: Checkout rucio containers repository
 #        uses: actions/checkout@v2
